package com.hurovia.blog.post.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jdk.jfr.Description;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

@Entity
@Table(name = "posts")
@Schema(description = "Data container used to store post data")
public class Post {
    public Long getPostId() {
        return postId;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Post(Long postId, String title, String content) {
        this.postId = postId;
        this.title = title;
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Id
    @Schema(description = "Unique Id to identify posts", accessMode = Schema.AccessMode.READ_ONLY)
    @NotBlank(message = "Unique Id will be autogenerated and cannot be empty")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "post_id", updatable = false, nullable = false)
    private Long postId;

    @NotBlank(message = "Post title cannot be empty")
    @Column(name = "post_title", nullable = false)
    @Schema(description = "Title of the post", accessMode = Schema.AccessMode.READ_WRITE)
    private String title;

    public Post(){

    }

    public Post(String title, String content) {
        this.title = title;
        this.content = content;
    }

    @Lob
    @Column(name = "post_content", columnDefinition = "MEDIUMTEXT")
    @Schema(description = "Blog content",  accessMode = Schema.AccessMode.READ_WRITE)
    private String content;

    public Instant getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Instant createdDate) {
        this.createdDate = createdDate;
    }

    @NotBlank(message = "Date and Time cannot be Empty")
    @Schema(description = "Posted Date and Time",accessMode = Schema.AccessMode.READ_ONLY)
    @CreationTimestamp
    @Column(name = "time_posted", updatable = false, nullable = false)
    private Instant createdDate;
}
